//! Port of `server/lib/relay/e2ee.js` — E2EE primitives + responder handshake
//! for the private relay (Layer 2).
//!
//! JS mirror contract: the JS module is itself a mirror of the normative TS in
//! `packages/ui/src/lib/relay/{protocol,crypto,handshake}.ts`; all three must
//! stay byte-compatible. The pinned vectors in [`self::byte_compat_tests`] were
//! generated by running the real JS implementation with fixed keys/nonces/IVs
//! and are the cross-implementation gate for this port.
//!
//! Crypto mapping: WebCrypto ECDH P-256 → `p256::ecdh::diffie_hellman`
//! (shared secret = 32-byte big-endian x-coordinate, identical to
//! `subtle.deriveBits(..., 256)`), HKDF-SHA256 (info `ompchamber-relay-v1`,
//! salt = handshake nonce, 64 bytes of output) → `hkdf`, AES-256-GCM frames
//! `[1B version][12B IV][ct+16B tag]` (WebCrypto and RustCrypto both append
//! the tag after the ciphertext).

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Key as AesKey, Nonce};
use hkdf::Hkdf;
use p256::elliptic_curve::sec1::{FromEncodedPoint, ToEncodedPoint};
use p256::{EncodedPoint, PublicKey, SecretKey};
use serde_json::Value;
use sha2::Sha256;

pub const RELAY_PROTOCOL_VERSION: u64 = 1;
pub const RELAY_HKDF_INFO: &[u8] = b"ompchamber-relay-v1";

/// Encrypted frame layout: `[1 byte version][12 byte IV][ciphertext + 16 byte GCM tag]`.
pub const ENCRYPTED_FRAME_VERSION: u8 = 1;
pub const ENCRYPTED_FRAME_IV_BYTES: usize = 12;
pub const ENCRYPTED_FRAME_HEADER_BYTES: usize = 1 + ENCRYPTED_FRAME_IV_BYTES;
pub const MAX_PLAINTEXT_FRAME_BYTES: usize = 64 * 1024;

/// Relay-assigned WebSocket close codes (subset the host needs).
pub const CLOSE_REKEY_MISMATCH: u16 = 1008;
pub const CLOSE_CHANNEL_FAILURE: u16 = 1011;

const HANDSHAKE_NONCE_BYTES: usize = 16;
const SESSION_KEY_BYTES: usize = 32;
const GCM_TAG_BYTES: usize = 16;
/// IV = 4-byte random per-direction prefix || 8-byte big-endian frame counter.
const IV_PREFIX_BYTES: usize = 4;
const IV_COUNTER_BYTES: usize = 8;

/// Error messages are pinned to the JS `RelayCryptoError` strings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RelayCryptoError(pub &'static str);

impl std::fmt::Display for RelayCryptoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

impl std::error::Error for RelayCryptoError {}

const INVALID_PUBLIC_JWK: &str = "invalid ECDH public key JWK";
const INVALID_PRIVATE_JWK: &str = "invalid ECDH private key JWK";

/// Generates an ECDH P-256 keypair (JS `generateEcdhKeyPair`). The scalar is
/// drawn from the OS RNG and retried until it lands in `[1, n-1]`.
pub fn generate_ecdh_key_pair() -> Result<(SecretKey, PublicKey), RelayCryptoError> {
    let mut bytes = [0u8; 32];
    for _ in 0..8 {
        rand::fill(&mut bytes);
        if let Ok(secret) = SecretKey::from_slice(&bytes) {
            let public = public_from_secret(&secret);
            return Ok((secret, public));
        }
    }
    Err(RelayCryptoError("entropy source failed"))
}

fn public_from_secret(secret: &SecretKey) -> PublicKey {
    // SecretKey::public_key() needs the arithmetic feature (enabled via ecdh);
    // derive the point through the scalar's public key accessor.
    PublicKey::from_secret_scalar(&secret.to_nonzero_scalar())
}

/// Public JWK reduced to the fields that define the point (JS
/// `exportPublicKeyJwk` returns `{ kty, crv, x, y }`).
pub fn export_public_key_jwk(public: &PublicKey) -> Value {
    let point = public.to_encoded_point(false);
    let bytes = point.as_bytes();
    serde_json::json!({
        "kty": "EC",
        "crv": "P-256",
        "x": bytes_to_base64_url(&bytes[1..33]),
        "y": bytes_to_base64_url(&bytes[33..65]),
    })
}

/// JS `importEcdhPublicKey` — accepts a raw JSON object; requires
/// `kty === 'EC'`, `crv === 'P-256'`, string `x`/`y`, and a valid curve point.
pub fn import_ecdh_public_key(jwk: &Value) -> Result<PublicKey, RelayCryptoError> {
    let get = |key: &str| -> Option<&str> {
        jwk.get(key)
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty())
    };
    let (kty, crv, x, y) = (
        get("kty"),
        get("crv"),
        jwk.get("x").and_then(Value::as_str),
        jwk.get("y").and_then(Value::as_str),
    );
    if kty != Some("EC") || crv != Some("P-256") || x.is_none() || y.is_none() {
        return Err(RelayCryptoError(INVALID_PUBLIC_JWK));
    }
    let x = base64_url_to_bytes(x.unwrap_or_default())
        .map_err(|_| RelayCryptoError(INVALID_PUBLIC_JWK))?;
    let y = base64_url_to_bytes(y.unwrap_or_default())
        .map_err(|_| RelayCryptoError(INVALID_PUBLIC_JWK))?;
    if x.len() != 32 || y.len() != 32 {
        return Err(RelayCryptoError(INVALID_PUBLIC_JWK));
    }
    let point = EncodedPoint::from_affine_coordinates(
        x.as_slice().try_into().expect("32 bytes"),
        y.as_slice().try_into().expect("32 bytes"),
        false,
    );
    PublicKey::from_encoded_point(&point)
        .into_option()
        .ok_or(RelayCryptoError(INVALID_PUBLIC_JWK))
}

/// JS `importEcdhPrivateKey` — needs a valid `d` scalar; the point fields are
/// accepted but the scalar alone defines the key.
pub fn import_ecdh_private_key(jwk: &Value) -> Result<SecretKey, RelayCryptoError> {
    let d = jwk
        .get("d")
        .and_then(Value::as_str)
        .ok_or(RelayCryptoError(INVALID_PRIVATE_JWK))?;
    let bytes = base64_url_to_bytes(d).map_err(|_| RelayCryptoError(INVALID_PRIVATE_JWK))?;
    if bytes.len() != 32 {
        return Err(RelayCryptoError(INVALID_PRIVATE_JWK));
    }
    SecretKey::from_slice(&bytes).map_err(|_| RelayCryptoError(INVALID_PRIVATE_JWK))
}

/// Stable fingerprint of a public key, used to detect rekey attempts on
/// re-hello. Mirrors `JSON.stringify({ crv, kty, x, y })` including
/// `JSON.stringify`'s omission of `undefined` values and its field order.
pub fn public_key_jwk_fingerprint(jwk: &Value) -> String {
    let mut out = String::from("{");
    let mut first = true;
    for field in ["crv", "kty", "x", "y"] {
        let Some(value) = jwk.get(field) else {
            continue;
        };
        if !first {
            out.push(',');
        }
        first = false;
        out.push_str(&format!("\"{field}\":"));
        match value {
            Value::String(s) => {
                let mut escaped = String::with_capacity(s.len() + 2);
                escaped.push('"');
                for ch in s.chars() {
                    match ch {
                        '"' => escaped.push_str("\\\""),
                        '\\' => escaped.push_str("\\\\"),
                        '\n' => escaped.push_str("\\n"),
                        '\r' => escaped.push_str("\\r"),
                        '\t' => escaped.push_str("\\t"),
                        c if (c as u32) < 0x20 => escaped.push_str(&format!("\\u{:04x}", c as u32)),
                        c => escaped.push(c),
                    }
                }
                escaped.push('"');
                out.push_str(&escaped);
            }
            other => out.push_str(&other.to_string()),
        }
    }
    out.push('}');
    out
}

pub fn generate_handshake_nonce() -> Result<[u8; HANDSHAKE_NONCE_BYTES], RelayCryptoError> {
    let mut nonce = [0u8; HANDSHAKE_NONCE_BYTES];
    rand::fill(&mut nonce);
    Ok(nonce)
}

/// Both sides call this with their own private key and the peer's public key;
/// ECDH yields the same shared secret, so the derived key pair matches.
#[derive(Clone)]
pub struct SessionKeys {
    pub client_to_host: Aes256Gcm,
    pub host_to_client: Aes256Gcm,
}

pub fn derive_session_keys(
    own_private_key: &SecretKey,
    peer_public_key: &PublicKey,
    handshake_nonce: &[u8],
) -> Result<SessionKeys, RelayCryptoError> {
    if handshake_nonce.len() != HANDSHAKE_NONCE_BYTES {
        return Err(RelayCryptoError("invalid handshake nonce length"));
    }
    let shared_secret = p256::ecdh::diffie_hellman(
        &own_private_key.to_nonzero_scalar(),
        peer_public_key.as_affine(),
    );
    let hkdf = Hkdf::<Sha256>::new(Some(handshake_nonce), shared_secret.raw_secret_bytes());
    let mut key_material = [0u8; SESSION_KEY_BYTES * 2];
    hkdf.expand(RELAY_HKDF_INFO, &mut key_material)
        .map_err(|_| RelayCryptoError("key derivation failed"))?;
    let import_aes =
        |bytes: &[u8]| -> Aes256Gcm { Aes256Gcm::new(AesKey::<Aes256Gcm>::from_slice(bytes)) };
    Ok(SessionKeys {
        client_to_host: import_aes(&key_material[..SESSION_KEY_BYTES]),
        host_to_client: import_aes(&key_material[SESSION_KEY_BYTES..]),
    })
}

fn write_counter(target: &mut [u8], counter: u64) {
    for (i, byte) in target.iter_mut().enumerate().take(IV_COUNTER_BYTES) {
        let shift = 8 * (IV_COUNTER_BYTES - 1 - i);
        *byte = ((counter >> shift) & 0xff) as u8;
    }
}

fn read_counter(source: &[u8]) -> u64 {
    let mut value: u64 = 0;
    for byte in source.iter().take(IV_COUNTER_BYTES) {
        value = (value << 8) | u64::from(*byte);
    }
    value
}

/// AES-256-GCM frame encryptor for one direction (JS `createFrameEncryptor`).
#[derive(Clone)]
pub struct FrameEncryptor {
    cipher: Aes256Gcm,
    iv_prefix: [u8; IV_PREFIX_BYTES],
    counter: u64,
}

impl FrameEncryptor {
    pub fn new(key: Aes256Gcm) -> Result<Self, RelayCryptoError> {
        let mut iv_prefix = [0u8; IV_PREFIX_BYTES];
        rand::fill(&mut iv_prefix);
        Ok(Self {
            cipher: key,
            iv_prefix,
            counter: 0,
        })
    }

    /// Test vector hook: the production constructor draws a random prefix;
    /// pinned byte-compat tests need a deterministic one.
    pub fn with_prefix(key: Aes256Gcm, iv_prefix: [u8; IV_PREFIX_BYTES]) -> Self {
        Self {
            cipher: key,
            iv_prefix,
            counter: 0,
        }
    }

    pub fn encrypt(&mut self, plaintext: &[u8]) -> Result<Vec<u8>, RelayCryptoError> {
        if plaintext.len() > MAX_PLAINTEXT_FRAME_BYTES {
            return Err(RelayCryptoError("plaintext frame exceeds maximum size"));
        }
        self.counter += 1;
        let mut iv = [0u8; ENCRYPTED_FRAME_IV_BYTES];
        iv[..IV_PREFIX_BYTES].copy_from_slice(&self.iv_prefix);
        write_counter(&mut iv[IV_PREFIX_BYTES..], self.counter);
        let ciphertext = self
            .cipher
            .encrypt(Nonce::from_slice(&iv), plaintext)
            .map_err(|_| RelayCryptoError("encryption failed"))?;
        let mut frame = Vec::with_capacity(ENCRYPTED_FRAME_HEADER_BYTES + ciphertext.len());
        frame.push(ENCRYPTED_FRAME_VERSION);
        frame.extend_from_slice(&iv);
        frame.extend_from_slice(&ciphertext);
        Ok(frame)
    }
}

/// Enforces strictly increasing per-direction counters: the relay WS preserves
/// ordering, so any regression or replay means tampering and must fail closed
/// (JS `createFrameDecryptor`).
#[derive(Clone)]
pub struct FrameDecryptor {
    cipher: Aes256Gcm,
    last_counter: u64,
}

impl FrameDecryptor {
    pub fn new(key: Aes256Gcm) -> Self {
        Self {
            cipher: key,
            last_counter: 0,
        }
    }

    pub fn decrypt(&mut self, frame: &[u8]) -> Result<Vec<u8>, RelayCryptoError> {
        if frame.len() < ENCRYPTED_FRAME_HEADER_BYTES + GCM_TAG_BYTES {
            return Err(RelayCryptoError("encrypted frame too short"));
        }
        if frame[0] != ENCRYPTED_FRAME_VERSION {
            return Err(RelayCryptoError("unsupported encrypted frame version"));
        }
        let iv = &frame[1..ENCRYPTED_FRAME_HEADER_BYTES];
        let counter = read_counter(&iv[IV_PREFIX_BYTES..]);
        if counter <= self.last_counter {
            return Err(RelayCryptoError("frame counter regression"));
        }
        let plaintext = self
            .cipher
            .decrypt(
                Nonce::from_slice(iv),
                &frame[ENCRYPTED_FRAME_HEADER_BYTES..],
            )
            .map_err(|_| RelayCryptoError("frame decryption failed"))?;
        self.last_counter = counter;
        Ok(plaintext)
    }
}

/// One established channel: encrypt host→client, decrypt client→host.
#[derive(Clone)]
pub struct Channel {
    pub encryptor: FrameEncryptor,
    pub decryptor: FrameDecryptor,
}

// ---------------------------------------------------------------------------
// base64url helpers (JS `bytesToBase64Url` / `base64UrlToBytes`)
// ---------------------------------------------------------------------------

pub fn bytes_to_base64_url(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0];
        let b1 = chunk.get(1).copied();
        let b2 = chunk.get(2).copied();
        out.push(ALPHABET[(b0 >> 2) as usize] as char);
        out.push(ALPHABET[(((b0 & 0x03) << 4) | (b1.unwrap_or(0) >> 4)) as usize] as char);
        if b1.is_some() {
            out.push(
                ALPHABET[(((b1.unwrap_or(0) & 0x0f) << 2) | (b2.unwrap_or(0) >> 6)) as usize]
                    as char,
            );
        }
        if b2.is_some() {
            out.push(ALPHABET[(b2.unwrap_or(0) & 0x3f) as usize] as char);
        }
    }
    out
}

pub fn base64_url_to_bytes(value: &str) -> Result<Vec<u8>, RelayCryptoError> {
    const fn alphabet_value(byte: u8) -> i8 {
        match byte {
            b'A'..=b'Z' => (byte - b'A') as i8,
            b'a'..=b'z' => (byte - b'a') as i8 + 26,
            b'0'..=b'9' => (byte - b'0') as i8 + 52,
            b'-' => 62,
            b'_' => 63,
            _ => -1,
        }
    }
    let bytes = value.as_bytes();
    if bytes.iter().any(|&b| alphabet_value(b) < 0) || bytes.len() % 4 == 1 {
        return Err(RelayCryptoError("invalid base64url input"));
    }
    let mut out = vec![0u8; value.len() * 3 / 4];
    let mut out_index = 0usize;
    let mut buffer: u32 = 0;
    let mut bits = 0u32;
    for &byte in bytes {
        buffer = (buffer << 6) | alphabet_value(byte) as u32;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out[out_index] = ((buffer >> bits) & 0xff) as u8;
            out_index += 1;
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Responder handshake state machine (host side). Mirror of createHostHandshake
// in packages/ui/src/lib/relay/handshake.ts.
//
// Fail-closed rules (from the spec):
// - a repeated identical `hello` re-sends `ready` (client retry race);
// - a `hello` with a DIFFERENT key on an established channel is a rekey
//   attack -> close 1008, never rekey in place;
// - plaintext after `ready`, or any decrypt failure -> close 1011.
// ---------------------------------------------------------------------------

pub enum HandshakeAction {
    /// Send this plaintext frame.
    SendText { text: String },
    /// Send `reply_text` first, then switch to encrypted frames.
    Established {
        batch: bool,
        reply_text: String,
        channel: Channel,
    },
    /// Drop the frame.
    Ignore,
    /// Close the socket with `close_code`.
    Fail {
        close_code: u16,
        reason: &'static str,
    },
}

enum ParsedHandshakeMessage {
    Hello {
        client_pub_jwk: Value,
        nonce: String,
        batch: bool,
    },
    Other,
}

fn parse_handshake_message(raw: &str) -> ParsedHandshakeMessage {
    let Ok(Value::Object(parsed)) = serde_json::from_str::<Value>(raw) else {
        return ParsedHandshakeMessage::Other;
    };
    if parsed.get("v").and_then(Value::as_u64) != Some(RELAY_PROTOCOL_VERSION) {
        return ParsedHandshakeMessage::Other;
    }
    // Unknown/missing capability flag = false = legacy behavior.
    let batch = parsed.get("batch") == Some(&Value::Bool(true));
    if parsed.get("t").and_then(Value::as_str) == Some("ready") {
        return ParsedHandshakeMessage::Other;
    }
    let is_hello = parsed.get("t").and_then(Value::as_str) == Some("hello")
        && parsed.get("nonce").map(Value::is_string) == Some(true)
        && parsed
            .get("clientPubJwk")
            .is_some_and(|value| value.is_object());
    if is_hello {
        ParsedHandshakeMessage::Hello {
            client_pub_jwk: parsed.get("clientPubJwk").cloned().unwrap_or(Value::Null),
            nonce: parsed
                .get("nonce")
                .and_then(Value::as_str)
                .unwrap_or_default()
                .to_string(),
            batch,
        }
    } else {
        ParsedHandshakeMessage::Other
    }
}

/// Host (responder) handshake. Feed every inbound text frame to
/// [`HostHandshake::handle_text`].
pub struct HostHandshake {
    host_enc_private_key: SecretKey,
    local_batch: bool,
    established: bool,
    accepted_client_key_fingerprint: Option<String>,
    ready_text: Option<String>,
}

impl HostHandshake {
    /// `batch` defaults true; set false to force legacy behavior.
    pub fn with_options(host_enc_private_key: SecretKey, batch: bool) -> Self {
        Self {
            host_enc_private_key,
            local_batch: batch,
            established: false,
            accepted_client_key_fingerprint: None,
            ready_text: None,
        }
    }

    pub fn new(host_enc_private_key: SecretKey) -> Self {
        Self::with_options(host_enc_private_key, true)
    }

    pub fn established(&self) -> bool {
        self.established
    }

    pub fn handle_text(&mut self, raw: &str) -> HandshakeAction {
        let message = parse_handshake_message(raw);
        let ParsedHandshakeMessage::Hello {
            client_pub_jwk,
            nonce,
            batch,
        } = message
        else {
            if self.established {
                return HandshakeAction::Fail {
                    close_code: CLOSE_CHANNEL_FAILURE,
                    reason: "plaintext frame on established channel",
                };
            }
            return HandshakeAction::Ignore;
        };
        let fingerprint = public_key_jwk_fingerprint(&client_pub_jwk);
        if self.accepted_client_key_fingerprint.is_some() {
            if self.ready_text.is_some()
                && self.accepted_client_key_fingerprint.as_deref() == Some(fingerprint.as_str())
            {
                // Client retried `hello` before our `ready` arrived — answer again.
                return HandshakeAction::SendText {
                    text: self.ready_text.clone().unwrap_or_default(),
                };
            }
            return HandshakeAction::Fail {
                close_code: CLOSE_REKEY_MISMATCH,
                reason: "rekey mismatch",
            };
        }
        let (client_public_key, nonce_bytes) = match import_ecdh_public_key(&client_pub_jwk)
            .and_then(|key| base64_url_to_bytes(&nonce).map(|nonce| (key, nonce)))
        {
            Ok((key, nonce)) if nonce.len() == HANDSHAKE_NONCE_BYTES => (key, nonce),
            _ => {
                return HandshakeAction::Fail {
                    close_code: CLOSE_CHANNEL_FAILURE,
                    reason: "malformed hello",
                };
            }
        };
        let keys =
            match derive_session_keys(&self.host_enc_private_key, &client_public_key, &nonce_bytes)
            {
                Ok(keys) => keys,
                Err(_) => {
                    return HandshakeAction::Fail {
                        close_code: CLOSE_CHANNEL_FAILURE,
                        reason: "key derivation failed",
                    };
                }
            };
        self.accepted_client_key_fingerprint = Some(fingerprint);
        // Batching runs only if both peers advertised it.
        let negotiated_batch = self.local_batch && batch;
        let ready_text = if negotiated_batch {
            r#"{"t":"ready","v":1,"batch":true}"#.to_string()
        } else {
            r#"{"t":"ready","v":1}"#.to_string()
        };
        self.ready_text = Some(ready_text.clone());
        self.established = true;
        // The production encryptor draws a random IV prefix; an entropy
        // failure at this point is a channel failure.
        let encryptor = match FrameEncryptor::new(keys.host_to_client.clone()) {
            Ok(encryptor) => encryptor,
            Err(_) => {
                return HandshakeAction::Fail {
                    close_code: CLOSE_CHANNEL_FAILURE,
                    reason: "key derivation failed",
                };
            }
        };
        HandshakeAction::Established {
            batch: negotiated_batch,
            reply_text: ready_text,
            channel: Channel {
                encryptor,
                decryptor: FrameDecryptor::new(keys.client_to_host.clone()),
            },
        }
    }
}
